In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/clementsilvestri/code/MitriBarbot/master_shelf/raw_data/recipes_ingredients.csv')

In [3]:
df.head()

,id,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags
0,71247,Cherry Streusel Cobbler,"I haven't made this in years, so I'm just gues...","[""cherry pie filling"", ""condensed milk"", ""melt...","[""2 (21 ounce) cans cherry pie filling"",""2...","[""Preheat oven to 375°F."", ""Spread cherry pie ...",6.0,1 (347 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
1,76133,Reuben and Swiss Casserole Bake,I think this is even better than a reuben sand...,"[""corned beef chopped"", ""sauerkraut cold water...","[""1/2-1 lb corned beef, cooked and choppe...","[""Set oven to 350 degrees F."", ""Butter a 9 x 1...",4.0,1 (207 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
2,503816,Yam-Pecan Recipe,A lady I work with heard me taking about ZWT a...,"[""unsalted butter"", ""vegetable oil"", ""all - pu...","[""3/4 cup unsalted butter, at room tempera...","[""Preheat oven to 350°F In a mixing bowl, usi...",8.0,1 (198 g),"[""time-to-make"", ""course"", ""main-ingredient"", ..."
3,418749,Tropical Orange Layer Cake,An easy and delicious cake. Great for a summ...,"[""orange cake mix"", ""instant vanilla pudding"",...","[""1 (18 ounce) pkge.orange cake mix"",""1 (3...","[""In a large mixing bowl, combine the first 6 ...",16.0,1 (191 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
4,392934,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,I was searching the web for something like thi...,"[""butter"", ""brown sugar"", ""granulated sugar"", ...","[""1/2 cup butter, room temperature "",""1/2 ...","[""Cream butter and sugars together."", ""Blend i...",24.0,1 (26 g),"[""15-minutes-or-less"", ""time-to-make"", ""course..."

In [4]:
df.shape

(500471, 9)

Supression des colonnes id et description

In [5]:
df = df.drop(columns=['id', 'description'])

In [6]:
df.isna().sum()

name                 0
ingredients          0
ingredients_raw     35
steps                0
servings           722
serving_size        35
tags                35
dtype: int64

In [7]:
df=df.dropna()

In [8]:
df.isna().sum()

name               0
ingredients        0
ingredients_raw    0
steps              0
servings           0
serving_size       0
tags               0
dtype: int64

In [9]:
df.loc[0,'ingredients']

'["cherry pie filling", "condensed milk", "melted margarine", "cinnamon", "nutmeg", "light brown sugar", "flour", "margarine", "chopped nuts", "oats", "butter - flavored cooking spray"]'

In [10]:
df.loc[0,'ingredients_raw']

'["2 (21   ounce) cans   cherry pie filling","2       eggs","1 (14   ounce) can   sweetened condensed milk (not evaporated)","1/4  cup   melted margarine","1/2  teaspoon    cinnamon","1/4  teaspoon    nutmeg","1/2  cup   firmly packed light brown sugar","1/2  cup    self-rising flour","1/4  cup    margarine","1/2  cup   chopped nuts (chef\\u0027s choice)","1/2  cup    quick-cooking oats","  butter-flavored cooking spray"]'

In [11]:
df.loc[0,'steps']

'["Preheat oven to 375°F.", "Spread cherry pie filling in a 8 x 8-inch square pan that has lightly been sprayed.", "In a medium-size bowl, beat eggs.", "Add milk, melted margarine, cinnamon, and nutmeg; mix well.", "Pour over cherry pie filling.", "In another medium size bowl, combine sugar and flour.", "Add margarine; with fork stir until crumbly.", "Add nuts and oats.", "Sprinkle over cobbler mixture.", "Bake 50 to 55 minutes or until set.", "Cool.", "Serve warm with ice cream or whipped topping.", "Refrigerate leftovers."]'

In [12]:
df.loc[0,'tags']

'["60-minutes-or-less", "time-to-make", "course", "main-ingredient", "cuisine", "preparation", "north-american", "cobblers-and-crisps", "desserts", "fruit", "oven", "pitted-fruit", "cherries", "equipment"]'

## Les colonnes ingredients, ingredients_raw, steps, tags sont des strings qui contiennent des listes.
## --> il faut les transformer en listes de strings qui pourront êtres extraites et exploitées

(le split ne fonctionne pas ici)

In [13]:
import ast

In [ ]:
errors=[]

def return_list(text):
    try :
        return ast.literal_eval(text)
    except (ValueError, SyntaxError) as e:
        errors.append((text, str(e)))
        return text

In [15]:
return_list(df.loc[0,'ingredients'])

['cherry pie filling',
 'condensed milk',
 'melted margarine',
 'cinnamon',
 'nutmeg',
 'light brown sugar',
 'flour',
 'margarine',
 'chopped nuts',
 'oats',
 'butter - flavored cooking spray']

In [16]:
df[['ingredients', 'ingredients_raw', 'steps', 'tags']] = df[['ingredients', 'ingredients_raw', 'steps', 'tags']] .map(return_list)

In [17]:
df.loc[0,'ingredients']

['cherry pie filling',
 'condensed milk',
 'melted margarine',
 'cinnamon',
 'nutmeg',
 'light brown sugar',
 'flour',
 'margarine',
 'chopped nuts',
 'oats',
 'butter - flavored cooking spray']

In [18]:
df.loc[0,'ingredients_raw']

['2 (21   ounce) cans   cherry pie filling',
 '2       eggs',
 '1 (14   ounce) can   sweetened condensed milk (not evaporated)',
 '1/4  cup   melted margarine',
 '1/2  teaspoon    cinnamon',
 '1/4  teaspoon    nutmeg',
 '1/2  cup   firmly packed light brown sugar',
 '1/2  cup    self-rising flour',
 '1/4  cup    margarine',
 "1/2  cup   chopped nuts (chef's choice)",
 '1/2  cup    quick-cooking oats',
 '  butter-flavored cooking spray']

In [19]:
df.loc[0,'steps']

['Preheat oven to 375°F.',
 'Spread cherry pie filling in a 8 x 8-inch square pan that has lightly been sprayed.',
 'In a medium-size bowl, beat eggs.',
 'Add milk, melted margarine, cinnamon, and nutmeg; mix well.',
 'Pour over cherry pie filling.',
 'In another medium size bowl, combine sugar and flour.',
 'Add margarine; with fork stir until crumbly.',
 'Add nuts and oats.',
 'Sprinkle over cobbler mixture.',
 'Bake 50 to 55 minutes or until set.',
 'Cool.',
 'Serve warm with ice cream or whipped topping.',
 'Refrigerate leftovers.']

In [20]:
df.loc[0,'tags']

['60-minutes-or-less',
 'time-to-make',
 'course',
 'main-ingredient',
 'cuisine',
 'preparation',
 'north-american',
 'cobblers-and-crisps',
 'desserts',
 'fruit',
 'oven',
 'pitted-fruit',
 'cherries',
 'equipment']

## Il faut retirer les lignes ayant des listes vides aux colonnes ingredients, ingredients_raw, steps et tags

In [31]:
df[df['ingredients'].apply(len)==0].count()

name               9992
ingredients        9992
ingredients_raw    9992
steps              9992
servings           9992
serving_size       9992
tags               9992
dtype: int64

In [32]:
df[df['ingredients_raw'].apply(len)==0].count()

name               0
ingredients        0
ingredients_raw    0
steps              0
servings           0
serving_size       0
tags               0
dtype: int64

In [33]:
df[df['steps'].apply(len)==0].count()

name               0
ingredients        0
ingredients_raw    0
steps              0
servings           0
serving_size       0
tags               0
dtype: int64

In [34]:
df[df['tags'].apply(len)==0].count()

name               0
ingredients        0
ingredients_raw    0
steps              0
servings           0
serving_size       0
tags               0
dtype: int64

In [35]:
df.loc[37, 'ingredients']

[]

In [36]:
df.loc[500458, 'ingredients']

[]

In [37]:
df = df[df["ingredients"].apply(len) > 0]

In [38]:
df[df['ingredients'].apply(len)==0].count()

name               0
ingredients        0
ingredients_raw    0
steps              0
servings           0
serving_size       0
tags               0
dtype: int64

In [39]:
df.shape

(489757, 7)

## Serving sizes contient 2 informations, il faut le splitter en 2 colonnes

In [42]:
df[['quantity', 'weight']] = df['serving_size'].str.extract(r'(\d+)\s*\((.*?)\)')

In [43]:
df

,name,ingredients,ingredients_raw,steps,servings,serving_size,tags,quantity,weight
0,Cherry Streusel Cobbler,"[cherry pie filling, condensed milk, melted ma...","[2 (21 ounce) cans cherry pie filling, 2 ...","[Preheat oven to 375°F., Spread cherry pie fil...",6.0,1 (347 g),"[60-minutes-or-less, time-to-make, course, mai...",1,347 g
1,Reuben and Swiss Casserole Bake,"[corned beef chopped, sauerkraut cold water, s...","[1/2-1 lb corned beef, cooked and chopped...","[Set oven to 350 degrees F., Butter a 9 x 13-i...",4.0,1 (207 g),"[60-minutes-or-less, time-to-make, course, mai...",1,207 g
2,Yam-Pecan Recipe,"[unsalted butter, vegetable oil, all - purpose...","[3/4 cup unsalted butter, at room temperat...","[Preheat oven to 350°F In a mixing bowl, usin...",8.0,1 (198 g),"[time-to-make, course, main-ingredient, cuisin...",1,198 g
3,Tropical Orange Layer Cake,"[orange cake mix, instant vanilla pudding, ora...","[1 (18 ounce) pkge.orange cake mix, 1 (3 ...","[In a large mixing bowl, combine the first 6 i...",16.0,1 (191 g),"[60-minutes-or-less, time-to-make, course, pre...",1,191 g
4,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,"[butter, brown sugar, granulated sugar, milk, ...","[1/2 cup butter, room temperature , 1/2 c...","[Cream butter and sugars together., Blend in m...",24.0,1 (26 g),"[15-minutes-or-less, time-to-make, course, mai...",1,26 g
...,...,...,...,...,...,...,...,...,...
500466,Sausage Meatloaf OAMC,"[ground beef, ground sausage, celery chopped, ...","[1 lb lean ground beef, 1/2 lb ground...","[Combine ground beef, sausage, celery, onion, ...",6.0,1 (244 g),"[time-to-make, course, main-ingredient, cuisin...",1,244 g
500467,Potato Salad With Olives Capers and Parmesan,"[red potatoes, fresh ground black pepper, virg...","[3 lbs small red potatoes, 2 tablespoon...","[Preheat oven to 375°., To prepare potatoes, p...",8.0,1 (223 g),"[time-to-make, course, main-ingredient, prepar...",1,223 g
500468,Chocolate Banana Pound Cake,"[butter, brown sugar, bananas, buttermilk, van...","[1 cup butter (room temperature), 2 lar...","[Preheat oven to 350 degrees., Grease and flou...",24.0,1 (99 g),"[time-to-make, course, main-ingredient, prepar...",1,99 g
500469,Cheesy Ground Beef and Rice Casserole,"[ground beef, medium onion chopped, brown rice...","[1 1/2 lbs ground beef, 1 medium onio...","[""*What I mean by ""partly drained"" with the mu...",6.0,1 (394 g),"[60-minutes-or-less, time-to-make, preparation]",1,394 g
500470,Chicken and Dumplings &ndash; Crock Pot,"[chicken cubed, frozen vegetables, onion, chic...","[1 lb chicken, cubed , 1 lb frozen v...","[Combine chicken, vegetables, onion and chicke...",6.0,1 (323 g),"[course, preparation, 5-ingredients-or-less, m...",1,323 g

## Maintenant il faut voir comment filtrer les lignes (ie trouver des recettes) en fonction d'une liste d'ingrédients donnée.

recette