In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/clementsilvestri/code/MitriBarbot/master_shelf/raw_data/recipes_ingredients.csv')

In [3]:
df.head()

,id,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags
0,71247,Cherry Streusel Cobbler,"I haven't made this in years, so I'm just gues...","[""cherry pie filling"", ""condensed milk"", ""melt...","[""2 (21 ounce) cans cherry pie filling"",""2...","[""Preheat oven to 375°F."", ""Spread cherry pie ...",6.0,1 (347 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
1,76133,Reuben and Swiss Casserole Bake,I think this is even better than a reuben sand...,"[""corned beef chopped"", ""sauerkraut cold water...","[""1/2-1 lb corned beef, cooked and choppe...","[""Set oven to 350 degrees F."", ""Butter a 9 x 1...",4.0,1 (207 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
2,503816,Yam-Pecan Recipe,A lady I work with heard me taking about ZWT a...,"[""unsalted butter"", ""vegetable oil"", ""all - pu...","[""3/4 cup unsalted butter, at room tempera...","[""Preheat oven to 350°F In a mixing bowl, usi...",8.0,1 (198 g),"[""time-to-make"", ""course"", ""main-ingredient"", ..."
3,418749,Tropical Orange Layer Cake,An easy and delicious cake. Great for a summ...,"[""orange cake mix"", ""instant vanilla pudding"",...","[""1 (18 ounce) pkge.orange cake mix"",""1 (3...","[""In a large mixing bowl, combine the first 6 ...",16.0,1 (191 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
4,392934,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,I was searching the web for something like thi...,"[""butter"", ""brown sugar"", ""granulated sugar"", ...","[""1/2 cup butter, room temperature "",""1/2 ...","[""Cream butter and sugars together."", ""Blend i...",24.0,1 (26 g),"[""15-minutes-or-less"", ""time-to-make"", ""course..."

Supression des colonnes id et description

In [4]:
df = df.drop(columns=['id', 'description'])

In [5]:
df=df.dropna()

In [6]:
df.reset_index(drop=True, inplace=True)

## Les colonnes ingredients, ingredients_raw, steps, tags sont des strings qui contiennent des listes.
## --> il faut les transformer en listes de strings qui pourront êtres extraites et exploitées

(le split ne fonctionne pas ici)

In [7]:
import ast

In [8]:
errors=[]

def return_list(text):
    try :
        return ast.literal_eval(text)
    except (ValueError, SyntaxError) as e:
        errors.append((text, str(e)))
        return text

In [9]:
df[['ingredients', 'ingredients_raw', 'steps', 'tags']] = df[['ingredients', 'ingredients_raw', 'steps', 'tags']] .map(return_list)

## Il faut retirer les lignes ayant des listes vides aux colonnes ingredients, ingredients_raw, steps et tags

In [10]:
df = df[df["ingredients"].apply(len) > 0]

In [11]:
df = df[df["ingredients_raw"].apply(len) > 0]

In [12]:
df = df[df["steps"].apply(len) > 0]

In [13]:
df = df[df["tags"].apply(len) > 0]

In [14]:
df.reset_index(drop=True, inplace=True)

## Serving sizes contient 2 informations, il faut le splitter en 2 colonnes

In [15]:
df[['quantity', 'weight']] = df['serving_size'].str.extract(r'(\d+)\s*\((.*?)\)')

In [16]:
df

,name,ingredients,ingredients_raw,steps,servings,serving_size,tags,quantity,weight
0,Cherry Streusel Cobbler,"[cherry pie filling, condensed milk, melted ma...","[2 (21 ounce) cans cherry pie filling, 2 ...","[Preheat oven to 375°F., Spread cherry pie fil...",6.0,1 (347 g),"[60-minutes-or-less, time-to-make, course, mai...",1,347 g
1,Reuben and Swiss Casserole Bake,"[corned beef chopped, sauerkraut cold water, s...","[1/2-1 lb corned beef, cooked and chopped...","[Set oven to 350 degrees F., Butter a 9 x 13-i...",4.0,1 (207 g),"[60-minutes-or-less, time-to-make, course, mai...",1,207 g
2,Yam-Pecan Recipe,"[unsalted butter, vegetable oil, all - purpose...","[3/4 cup unsalted butter, at room temperat...","[Preheat oven to 350°F In a mixing bowl, usin...",8.0,1 (198 g),"[time-to-make, course, main-ingredient, cuisin...",1,198 g
3,Tropical Orange Layer Cake,"[orange cake mix, instant vanilla pudding, ora...","[1 (18 ounce) pkge.orange cake mix, 1 (3 ...","[In a large mixing bowl, combine the first 6 i...",16.0,1 (191 g),"[60-minutes-or-less, time-to-make, course, pre...",1,191 g
4,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,"[butter, brown sugar, granulated sugar, milk, ...","[1/2 cup butter, room temperature , 1/2 c...","[Cream butter and sugars together., Blend in m...",24.0,1 (26 g),"[15-minutes-or-less, time-to-make, course, mai...",1,26 g
...,...,...,...,...,...,...,...,...,...
489752,Sausage Meatloaf OAMC,"[ground beef, ground sausage, celery chopped, ...","[1 lb lean ground beef, 1/2 lb ground...","[Combine ground beef, sausage, celery, onion, ...",6.0,1 (244 g),"[time-to-make, course, main-ingredient, cuisin...",1,244 g
489753,Potato Salad With Olives Capers and Parmesan,"[red potatoes, fresh ground black pepper, virg...","[3 lbs small red potatoes, 2 tablespoon...","[Preheat oven to 375°., To prepare potatoes, p...",8.0,1 (223 g),"[time-to-make, course, main-ingredient, prepar...",1,223 g
489754,Chocolate Banana Pound Cake,"[butter, brown sugar, bananas, buttermilk, van...","[1 cup butter (room temperature), 2 lar...","[Preheat oven to 350 degrees., Grease and flou...",24.0,1 (99 g),"[time-to-make, course, main-ingredient, prepar...",1,99 g
489755,Cheesy Ground Beef and Rice Casserole,"[ground beef, medium onion chopped, brown rice...","[1 1/2 lbs ground beef, 1 medium onio...","[""*What I mean by ""partly drained"" with the mu...",6.0,1 (394 g),"[60-minutes-or-less, time-to-make, preparation]",1,394 g
489756,Chicken and Dumplings &ndash; Crock Pot,"[chicken cubed, frozen vegetables, onion, chic...","[1 lb chicken, cubed , 1 lb frozen v...","[Combine chicken, vegetables, onion and chicke...",6.0,1 (323 g),"[course, preparation, 5-ingredients-or-less, m...",1,323 g

# Interessons-nous à la colonne Tags

In [17]:
df['tags'][0]

['60-minutes-or-less',
 'time-to-make',
 'course',
 'main-ingredient',
 'cuisine',
 'preparation',
 'north-american',
 'cobblers-and-crisps',
 'desserts',
 'fruit',
 'oven',
 'pitted-fruit',
 'cherries',
 'equipment']

In [18]:
for i in range(0,100):
    print(df['tags'][i][0])

60-minutes-or-less
60-minutes-or-less
time-to-make
60-minutes-or-less
15-minutes-or-less
time-to-make
weeknight
30-minutes-or-less
time-to-make
60-minutes-or-less
30-minutes-or-less
weeknight
time-to-make
15-minutes-or-less
course
15-minutes-or-less
time-to-make
15-minutes-or-less
15-minutes-or-less
15-minutes-or-less
15-minutes-or-less
lactose
time-to-make
lactose
30-minutes-or-less
15-minutes-or-less
30-minutes-or-less
30-minutes-or-less
time-to-make
time-to-make
60-minutes-or-less
60-minutes-or-less
15-minutes-or-less
weeknight
time-to-make
time-to-make
60-minutes-or-less
weeknight
30-minutes-or-less
15-minutes-or-less
time-to-make
weeknight
30-minutes-or-less
60-minutes-or-less
ham
time-to-make
15-minutes-or-less
30-minutes-or-less
60-minutes-or-less
60-minutes-or-less
30-minutes-or-less
course
ham
60-minutes-or-less
60-minutes-or-less
time-to-make
60-minutes-or-less
15-minutes-or-less
time-to-make
30-minutes-or-less
30-minutes-or-less
60-minutes-or-less
60-minutes-or-less
time-to-make
60-minutes-or-less
time-to-make
60-minutes-or-less
60-minutes-or-less
60-minutes-or-less
weeknight
course
60-minutes-or-less
15-minutes-or-less
weeknight
15-minutes-or-less
30-minutes-or-less
time-to-make
time-to-make
weeknight
15-minutes-or-less
60-minutes-or-less
15-minutes-or-less
time-to-make
15-minutes-or-less
weeknight
time-to-make
30-minutes-or-less
60-minutes-or-less
15-minutes-or-less
time-to-make
15-minutes-or-less
60-minutes-or-less
60-minutes-or-less
30-minutes-or-less
30-minutes-or-less
15-minutes-or-less
time-to-make
60-minutes-or-less
30-minutes-or-less
60-minutes-or-less

In [19]:
for i in range(0,100):
    print(df['tags'][i][1])

time-to-make
time-to-make
course
time-to-make
time-to-make
preparation
15-minutes-or-less
time-to-make
course
time-to-make
time-to-make
30-minutes-or-less
course
time-to-make
main-ingredient
time-to-make
course
time-to-make
time-to-make
time-to-make
time-to-make
60-minutes-or-less
course
60-minutes-or-less
time-to-make
time-to-make
time-to-make
time-to-make
course
course
time-to-make
time-to-make
time-to-make
time-to-make
course
course
time-to-make
60-minutes-or-less
time-to-make
time-to-make
course
60-minutes-or-less
time-to-make
time-to-make
60-minutes-or-less
course
time-to-make
time-to-make
time-to-make
time-to-make
time-to-make
main-ingredient
15-minutes-or-less
time-to-make
time-to-make
course
time-to-make
time-to-make
course
time-to-make
time-to-make
time-to-make
time-to-make
course
time-to-make
preparation
time-to-make
time-to-make
time-to-make
time-to-make
main-ingredient
time-to-make
time-to-make
time-to-make
time-to-make
time-to-make
course
course
time-to-make
time-to-make
time-to-make
time-to-make
course
time-to-make
time-to-make
course
time-to-make
time-to-make
time-to-make
course
time-to-make
time-to-make
time-to-make
time-to-make
time-to-make
time-to-make
course
time-to-make
time-to-make
time-to-make

In [20]:
for i in range(0,100):
    print(df['tags'][i][2])

course
course
main-ingredient
course
course
presentation
time-to-make
course
main-ingredient
course
course
time-to-make
preparation
course
preparation
course
preparation
course
course
course
course
time-to-make
main-ingredient
time-to-make
course
course
course
course
main-ingredient
main-ingredient
course
course
course
course
main-ingredient
main-ingredient
course
time-to-make
course
course
preparation
time-to-make
course
course
time-to-make
main-ingredient
course
main-ingredient
course
course
main-ingredient
preparation
time-to-make
course
course
main-ingredient
course
course
main-ingredient
course
course
course
course
main-ingredient
course
bread-machine
course
course
course
course
main-dish
course
course
course
course
course
main-ingredient
main-ingredient
course
course
course
main-ingredient
cuisine
course
course
preparation
course
course
preparation
main-ingredient
course
course
course
course
preparation
course
main-ingredient
course
course
course

In [21]:
time_to_make = ['15-minutes-or-less', '30-minutes-or-less', '60-minutes-or-less'] #Je n'ai pas compté weeknight

In [22]:
for i in range(0,100):
    print(len(df['tags'][i]))

14
12
21
11
10
5
22
13
22
14
16
16
13
12
12
19
11
25
16
18
14
21
10
26
5
9
19
18
26
16
16
16
9
19
14
32
19
28
17
21
10
22
18
6
10
17
17
9
16
21
8
15
31
24
24
8
18
19
25
25
13
16
14
24
16
8
25
20
13
19
5
15
16
24
39
30
14
19
15
8
10
8
18
19
14
6
9
21
6
25
12
24
15
9
3
19
18
18
16
10

In [23]:
for i in range(0, 100):
        if (time_to_make[0] in df['tags'][i]) or (time_to_make[1] in df['tags'][i]) or (time_to_make[2] in df['tags'][i]):
            print(i, 'ok')
        else:
            print(i, 'not ok')

0 ok
1 ok
2 not ok
3 ok
4 ok
5 not ok
6 ok
7 ok
8 not ok
9 ok
10 ok
11 ok
12 not ok
13 ok
14 not ok
15 ok
16 not ok
17 ok
18 ok
19 ok
20 ok
21 ok
22 not ok
23 ok
24 ok
25 ok
26 ok
27 ok
28 not ok
29 not ok
30 ok
31 ok
32 ok
33 not ok
34 not ok
35 not ok
36 ok
37 ok
38 ok
39 ok
40 not ok
41 ok
42 ok
43 ok
44 ok
45 not ok
46 ok
47 ok
48 ok
49 ok
50 ok
51 not ok
52 ok
53 ok
54 ok
55 not ok
56 ok
57 ok
58 not ok
59 ok
60 ok
61 ok
62 ok
63 not ok
64 ok
65 not ok
66 ok
67 ok
68 ok
69 not ok
70 not ok
71 ok
72 ok
73 not ok
74 ok
75 ok
76 not ok
77 not ok
78 not ok
79 ok
80 ok
81 ok
82 not ok
83 ok
84 not ok
85 not ok
86 ok
87 ok
88 ok
89 not ok
90 ok
91 ok
92 ok
93 ok
94 ok
95 ok
96 not ok
97 ok
98 ok
99 ok

In [24]:
for i in range(0, 100):
        if not((time_to_make[0] in df['tags'][i]) or (time_to_make[1] in df['tags'][i]) or (time_to_make[2] in df['tags'][i])):
            print(i, 'not ok')
        else:
            print(i, 'ok')

0 ok
1 ok
2 not ok
3 ok
4 ok
5 not ok
6 ok
7 ok
8 not ok
9 ok
10 ok
11 ok
12 not ok
13 ok
14 not ok
15 ok
16 not ok
17 ok
18 ok
19 ok
20 ok
21 ok
22 not ok
23 ok
24 ok
25 ok
26 ok
27 ok
28 not ok
29 not ok
30 ok
31 ok
32 ok
33 not ok
34 not ok
35 not ok
36 ok
37 ok
38 ok
39 ok
40 not ok
41 ok
42 ok
43 ok
44 ok
45 not ok
46 ok
47 ok
48 ok
49 ok
50 ok
51 not ok
52 ok
53 ok
54 ok
55 not ok
56 ok
57 ok
58 not ok
59 ok
60 ok
61 ok
62 ok
63 not ok
64 ok
65 not ok
66 ok
67 ok
68 ok
69 not ok
70 not ok
71 ok
72 ok
73 not ok
74 ok
75 ok
76 not ok
77 not ok
78 not ok
79 ok
80 ok
81 ok
82 not ok
83 ok
84 not ok
85 not ok
86 ok
87 ok
88 ok
89 not ok
90 ok
91 ok
92 ok
93 ok
94 ok
95 ok
96 not ok
97 ok
98 ok
99 ok

In [33]:
def remove_no_time(liste):
    if not any (t in liste for t in time_to_make):
        liste.clear()

In [34]:
df.shape

(489757, 9)

In [35]:
df['tags']

0         [60-minutes-or-less, time-to-make, course, mai...
1         [60-minutes-or-less, time-to-make, course, mai...
2         [time-to-make, course, main-ingredient, cuisin...
3         [60-minutes-or-less, time-to-make, course, pre...
4         [15-minutes-or-less, time-to-make, course, mai...
                                ...
489752    [time-to-make, course, main-ingredient, cuisin...
489753    [time-to-make, course, main-ingredient, prepar...
489754    [time-to-make, course, main-ingredient, prepar...
489755      [60-minutes-or-less, time-to-make, preparation]
489756    [course, preparation, 5-ingredients-or-less, m...
Name: tags, Length: 489757, dtype: object

In [36]:
df['tags'].apply(remove_no_time)

0         None
1         None
2         None
3         None
4         None
          ...
489752    None
489753    None
489754    None
489755    None
489756    None
Name: tags, Length: 489757, dtype: object

In [37]:
df = df[df["tags"].apply(len) > 0]

In [38]:
df.reset_index(drop=True, inplace=True)

In [39]:
df.shape

(349938, 9)

In [40]:
df['tags'][2]

['60-minutes-or-less',
 'time-to-make',
 'course',
 'preparation',
 'for-large-groups',
 'low-protein',
 'desserts',
 'cakes',
 'dietary',
 'low-in-something',
 'number-of-servings']

In [41]:
unique_tags = (df['tags'].explode().unique())
len(unique_tags)

516

In [42]:
unique_tags

array(['60-minutes-or-less', 'time-to-make', 'course', 'main-ingredient',
       'cuisine', 'preparation', 'north-american', 'cobblers-and-crisps',
       'desserts', 'fruit', 'oven', 'pitted-fruit', 'cherries',
       'equipment', 'casseroles', 'main-dish', 'eggs-dairy', 'cheese',
       'dietary', 'for-large-groups', 'low-protein', 'cakes',
       'low-in-something', 'number-of-servings', '15-minutes-or-less',
       'cookies-and-brownies', 'chocolate', 'weeknight', 'occasion',
       '5-ingredients-or-less', 'pork', 'easy', 'beginner-cook',
       'high-protein', 'low-carb', 'high-in-something', 'meat',
       'pork-chops', '3-steps-or-less', '30-minutes-or-less',
       'pies-and-tarts', 'crusts-pastry-dough-2', 'low-sodium', 'breads',
       'vegetarian', 'rolls-biscuits', 'comfort-food', 'brunch',
       'taste-mood', 'salads', 'pasta', 'potluck', 'picnic',
       'low-cholesterol', 'pasta-rice-and-grains', 'elbow-macaroni',
       'to-go', 'vegetables', 'diabetic', 'dinner-party',
       'salad-dressings', 'for-1-or-2', 'pancakes-and-waffles',
       'breakfast', 'french', 'european', 'condiments-etc', 'no-cook',
       'holiday-event', 'kosher', 'technique', 'lunch', 'american',
       'southern-united-states', 'southwestern-united-states',
       'kid-friendly', 'inexpensive', 'tropical-fruit', 'bananas',
       'fudge', 'microwave', 'candy', 'seafood', 'cajun', 'stews',
       'shrimp', 'creole', 'shellfish', 'canadian', 'lactose', 'potatoes',
       'asian', 'indian', 'vegan', 'one-dish-meal', 'gluten-free',
       'free-of-something', 'cauliflower', 'poultry', 'spanish',
       'barbecue', 'chicken', 'stove-top', 'mushrooms', 'chicken-breasts',
       'savory', 'grilling', 'side-dishes', 'south-west-pacific', 'fish',
       'tuna', 'polynesian', 'saltwater-fish', 'onions', 'tomatoes',
       'healthy', 'low-fat', 'low-saturated-fat', 'gumbo', 'soul',
       'lamb-sheep', 'australian', 'puddings-and-mousses', 'gelatin',
       'citrus', 'oranges', 'beef', 'ground-beef', 'steaks', 'appetizers',
       'beans', 'dips', 'low-calorie', 'black-beans', 'healthy-2', 'corn',
       'berries', 'strawberries', 'greens', 'ham', 'beverages',
       'cocktails', 'melons', 'brown-bag', 'camping', 'clear-soups',
       'laotian', 'soups-stews', 'fall', 'seasonal', 'sauces', 'roast',
       'marinades-and-rubs', 'apples', 'presentation', 'served-hot',
       'summer', 'squash', 'drop-cookies', 'scottish', 'christmas',
       'from-scratch', 'middle-eastern', 'gifts', 'snacks', 'bar-cookies',
       'omelets-and-frittatas', 'savory-pies', 'eggs', 'mexican',
       'tex-mex', 'crab', 'spicy', 'very-low-carbs', 'whole-chicken',
       'smoothies', 'romantic', 'punch', 'oamc-freezer-make-ahead',
       'st-patricks-day', 'served-cold', 'non-alcoholic', 'rice', 'greek',
       'freezer', 'white-rice', 'muffins', 'quick-breads',
       'cake-fillings-and-frostings', 'sweet',
       'fillings-and-frostings-chocolate', 'bisques-cream-soups',
       'heirloom-historical', 'winter', 'egg-free', 'grapes', 'nuts',
       'thanksgiving', 'hand-formed-cookies', 'italian', 'brown-rice',
       'short-grain-rice', 'grains', 'cheesecake', 'soy-tofu', 'brownies',
       'finger-food', 'lettuces', 'english', 'sandwiches', 'veal',
       'food-processor-blender', 'raspberries', 'small-appliance',
       'peppers', 'broccoli', 'salmon', 'midwestern', 'african',
       'moroccan', 'high-calcium', 'curries', 'carrots', 'wedding',
       'pasta-shells', 'spinach', 'frozen-desserts', 'pears',
       'refrigerator', 'pies', 'oaxacan', 'savory-sauces',
       'simply-potatoes', 'pizza', 'broil', 'pacific-northwest',
       'wild-game', 'lime', 'clams', 'stocks', 'pumpkin',
       'independence-day', 'beijing', 'chinese', 'pineapple', 'mahi-mahi',
       'new-years', 'valentines-day', 'shakes', 'novelty', 'thai',
       'spaghetti', 'ravioli-tortellini', 'jams-and-preserves',
       'stir-fry', 'pork-loins', 'korean', 'german', 'spring',
       'californian', 'kiwifruit', 'asparagus', 'lemon',
       'long-grain-rice', 'toddler-friendly', 'chili',
       'chick-peas-garbanzos', 'garnishes', 'copycat',
       'stuffings-dressings', 'steam', 'granola-and-porridge',
       'british-columbian', 'mixer', 'bok-choys', 'pork-sausage',
       'halloween', 'chicken-thighs-legs', 'wings', 'duck',
       'duck-breasts', 'brazilian', 'south-american', 'salsas', 'mango',
       'turkey', 'peaches', 'native-american', 'mussels', 'cod',
       'spreads', 'artichoke', 'new-zealand', 'rolled-cookies',
       'blueberries', 'dutch', 'bacon', 'nigerian', 'steak', 'pot-pie',
       'papaya', 'superbowl', 'pakistani', 'yams-sweet-potatoes',
       'chocolate-chip-cookies', 'manicotti', 'caribbean',
       'central-american', 'northeastern-united-states', 'celebrity',
       'chard', 'lasagna', 'japanese', 'deep-fry', 'rabbit', 'halibut',
       'cupcakes', 'hungarian', 'jewish-ashkenazi', 'austrian', 'easter',
       'czech', 'hanukkah', 'yeast', 'scandinavian', 'argentine',
       'lentils', 'tarts', 'kwanzaa', 'mardi-gras-carnival', 'burgers',
       'hidden-valley-ranch', 'crock-pot-slow-cooker', 'ice-cream',
       'whole-turkey', 'zucchini', 'scones', 'indonesian', 'tempeh',
       'penne', 'sole-and-flounder', 'freshwater-fish', 'whitefish',
       'ontario', 'collard-greens', 'green-yellow-beans', 'swedish',
       'chowders', 'sweet-sauces', 'coconut', 'bass', 'lebanese', 'swiss',
       'chilean', 'baking', 'coffee-cakes', 'scallops', 'avocado',
       'biscotti', 'peanut-butter', 'jellies', 'canning', 'water-bath',
       'irish', 'pork-ribs', 'birthday', 'cantonese', 'pet-food',
       'infant-baby-friendly', 'quebec', 'chinese-new-year', 'portuguese',
       'high-fiber', 'dairy-free', 'oysters', 'catfish',
       'amish-mennonite', 'hawaiian', 'nut-free', 'pressure-cooker',
       'quiche', 'turkey-breasts', 'cooking-mixes', 'jewish-sephardi',
       'roast-beef', 'sourdough', 'herb-and-spice-mixes', 'south-african',
       'rosh-hashana', 'turkish', 'cambodian', 'vietnamese', 'cuban',
       'russian', 'no-shell-fish', 'szechuan', 'danish', 'ethiopian',
       'leftovers', 'meatloaf', 'smoker', 'polish', 'unprocessed-freezer',
       'lobster', 'bread-machine', 'mashed-potatoes', 'meatballs',
       'norwegian', 'micro-melanesia', 'eggplant', 'peruvian', 'hunan',
       'octopus', 'malaysian', 'angolan', 'non-food-products',
       'bath-beauty', 'homeopathy-remedies', 'beef-sausage', 'plums',
       'chutneys', 'crawfish', 'passover', 'flat-shapes', 'egyptian',
       'ramadan', 'veggie-burgers', 'squid', 'reynolds-wrap',
       'iranian-persian', 'beef-organ-meats', 'beef-liver', 'bizarre',
       'trout', 'pennsylvania-dutch', 'finnish', 'cinco-de-mayo', 'baja',
       'college', 'puerto-rican', '4-hours-or-less', 'welsh',
       'mothers-day', 'fathers-day', 'filipino', 'tilapia', 'sudanese',
       'saudi-arabian', 'deer', 'super-bowl', 'belgian', 'iraqi',
       'a1-sauce', 'macaroni-and-cheese', 'pressure-canning',
       'whole-duck', 'goose', 'ragu-recipe-contest', 'medium-grain-rice',
       'icelandic', 'oatmeal', 'nepalese', 'sugar-cookies',
       'april-fools-day', 'chicken-livers', 'household-cleansers',
       'memorial-day', 'labor-day', 'dips-lunch-snacks', 'orange-roughy',
       '1-day-or-more', 'turkey-burgers', 'ecuadorean', 'dehydrator',
       'venezuelan', 'costa-rican', 'quail', 'rosh-hashanah',
       'prepared-potatoes', 'elk', 'desserts-fruit', 'desserts-easy',
       'palestinian', 'guatemalan', 'colombian', 'libyan', 'beef-ribs',
       'halloween-cupcakes', 'georgian', 'pheasant', 'moose', 'brewing',
       'fourth-of-july', 'congolese', 'perch',
       'pasta-rice-and-grains-elbow-macaroni', 'breakfast-eggs',
       'eggs-breakfast', 'honduran', 'mongolian', 'pasta-elbow-macaroni',
       'pickeral', 'somalian', 'halloween-cakes',
       'heirloom-historical-recipes', 'beef-kidney',
       'high-in-something-diabetic-friendly', 'cabbage',
       'halloween-cocktails', 'simply-potatoes2', 'bear', 'namibian',
       'irish-st-patricks-day', 'queso-for-all',
       'casseroles-one-dish-meal', 'no-bake-cookies'], dtype=object)

In [43]:
type_dish = ['cobblers-and-crisps','cakes','cookies-and-brownies','pork-chops','pies-and-tarts','breads','rolls-biscuits','salads','pasta','vegetables','salad-dressings',
             'pancakes-and-waffles','candy','stews','barbecue','puddings-and-mousses','beverages','cocktails','clear-soups','sauces','roast','marinades-and-rubs',
             'bar-cookies','omelets-and-frittatas','savory-pies','quick-breads','sweet','bisques-cream-soups','cheesecake','brownies','sandwiches','pies','savory-sauces',
             'shakes','spaghetti','ravioli-tortellini','jams-and-preserves','pork-loins','chili','garnishes','granola-and-porridge','rolled-cookies','pot-pie','chocolate-chip-cookies',
             'manicotti','lasagna','cupcakes','tarts','burgers','ice-cream','scones','tempeh','penne','chowders','sweet-sauces','coffee-cakes','biscotti','pork-ribs','quiche','roast-beef',
             'meatloaf','mashed-potatoes','meatballs','chutneys','veggie-burgers','macaroni-and-cheese','oatmeal','sugar-cookies','labor-day','dips-lunch-snacks','turkey-burgers',
             'prepared-potatoes','desserts-fruit','desserts-easy','halloween-cupcakes','breakfast-eggs','eggs-breakfast','halloween-cakes','halloween-cocktails','no-bake-cookies']

In [44]:

type_diet = ['dietary','low-protein','high-protein','low-carb','low-sodium','vegetarian','comfort-food','low-cholesterol','pasta-rice-and-grains','diabetic',
             'kosher','kid-friendly','inexpensive','gluten-free','healthy','low-fat','low-saturated-fat','low-calorie','healthy-2','spicy','very-low-carbs','heirloom-historical',
             'egg-free','high-calcium','toddler-friendly','pet-food','infant-baby-friendly','high-fiber','dairy-free','no-shell-fish','heirloom-historical-recipes']

In [45]:

type_occasion = ['brunch','potluck','picnic','to-go','dinner-party','barbecue','camping','fall','summer','christmas','romantic','st-patricks-day','winter','thanksgiving',
                 'independence-day','new-years','wedding','valentines-day','spring','halloween','easter','hanukkah','kwanzaa','mardi-gras-carnival','birthday','chinese-new-year'
                 'rosh-hashana','ramadan','cinco-de-mayo','mothers-day','fathers-day','super-bowl','april-fools-day','memorial-day','rosh-hashanah','fourth-of-july','irish-st-patricks-day']

In [46]:
type_meal = ['desserts','main-dish','brunch','potluck','picnic','dinner-party','breakfast','lunch',
             'side-dishes','appetizers','beverages','cocktails','snacks','frozen-desserts','dips-lunch-snacks','one-dish-meal','barbecue','finger-food','non-food-products']

In [47]:
type_origin = ['north-american','french','european','american','southern-united-states','southwestern-united-states','cajun','creole','canadian','asian','indian','spanish','south-west-pacific',
               'australian','laotian','scottish','middle-eastern','mexican','tex-mex','greek','italian','english','midwestern','african','moroccan','pacific-northwest',
               'beijing','chinese','thai','korean','german','californian','british-columbian','brazilian','south-american','native-american','new-zealand',
               'dutch','nigerian','pakistani','caribbean','central-american','northeastern-united-states','japanese','hungarian','jewish-ashkenazi','austrian',
               'czech','scandinavian','argentine','indonesian','swedish','lebanese','swiss','chilean','irish','quebec','portuguese','amish-mennonite','hawaiian',
               'jewish-sephardi','south-african','turkish','cambodian','vietnamese','cuban','russian','szechuan','danish','ethiopian','polish','norwegian','micro-melanesia',
               'peruvian','hunan','malaysian','angolan','iranian-persian','pennsylvania-dutch','finnish','filipino','sudanese','saudi-arabian','belgian','iraqi',
               'icelandic','nepalese','ecuadorean','venezuelan','costa-rican','palestinian','guatemalan','colombian','libyan','georgian','congolese','honduran','mongolian',
               'somalian','namibian','welsh']

In [48]:
type_dish.sort()
type_diet.sort()
type_occasion.sort()
type_origin.sort()

In [ ]:
def type_column(liste, type_liste):
    matched_elements = []
    for element in type_liste:
        if element in liste:
            matched_elements.append(element)
    return matched_elements

In [ ]:
df_copy = df

In [63]:
df_copy['type_dish'] = df_copy['tags'].apply(lambda x: type_column(x, type_dish))

In [64]:
df_copy

,name,ingredients,ingredients_raw,steps,servings,serving_size,tags,quantity,weight,type_dish
0,Cherry Streusel Cobbler,"[cherry pie filling, condensed milk, melted ma...","[2 (21 ounce) cans cherry pie filling, 2 ...","[Preheat oven to 375°F., Spread cherry pie fil...",6.0,1 (347 g),"[60-minutes-or-less, time-to-make, course, mai...",1,347 g,[cobblers-and-crisps]
1,Reuben and Swiss Casserole Bake,"[corned beef chopped, sauerkraut cold water, s...","[1/2-1 lb corned beef, cooked and chopped...","[Set oven to 350 degrees F., Butter a 9 x 13-i...",4.0,1 (207 g),"[60-minutes-or-less, time-to-make, course, mai...",1,207 g,[]
2,Tropical Orange Layer Cake,"[orange cake mix, instant vanilla pudding, ora...","[1 (18 ounce) pkge.orange cake mix, 1 (3 ...","[In a large mixing bowl, combine the first 6 i...",16.0,1 (191 g),"[60-minutes-or-less, time-to-make, course, pre...",1,191 g,[cakes]
3,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,"[butter, brown sugar, granulated sugar, milk, ...","[1/2 cup butter, room temperature , 1/2 c...","[Cream butter and sugars together., Blend in m...",24.0,1 (26 g),"[15-minutes-or-less, time-to-make, course, mai...",1,26 g,[cookies-and-brownies]
4,Teriyaki Pork Chops,"[teriyaki sauce, pork chops]","[1 (16 ounce) bottle teriyaki sauce, 4 ...",[I like to marinade them overnight in a ziploc...,4.0,1 (313 g),"[weeknight, 15-minutes-or-less, time-to-make, ...",1,313 g,[pork-chops]
...,...,...,...,...,...,...,...,...,...,...
349933,Soy-sesame Roasted Squash,"[small yellow squash zucchini, cloves garlic p...",[2 lbs small yellow squash or 2 lbs z...,"[Heat oven to 500F., On a large baking sheet,t...",6.0,1 (116 g),"[15-minutes-or-less, time-to-make, course, mai...",1,116 g,[vegetables]
349934,Korova Cookies,"[Dutch - processed cocoa powder, baking soda, ...","[1 1/4 cups all-purpose flour, 1/3 cup ...","[""Sift the flour, cocoa, and baking soda."", ""P...",36.0,1 (19 g),"[60-minutes-or-less, time-to-make, course, pre...",1,19 g,[cookies-and-brownies]
349935,Pork Loin With Apples,"[boneless pork loin roast, pork stuffing, all ...","[3 -4 lbs boneless pork loin roast, 6 o...","[Slice pocket in boneless pork roast., Set asi...",8.0,1 (327 g),"[60-minutes-or-less, time-to-make, course, mai...",1,327 g,[]
349936,Awesome Soft Baked Chocolate Chip Cookies,"[baking soda, butter, granulated sugar, brown ...","[2 1/4 cups all-purpose flour, 1 teaspoo...","[""PREHEAT oven to 375°F."", ""COMBINE flour, bak...",1.0,1 (1424 g),"[30-minutes-or-less, time-to-make, course, pre...",1,1424 g,[cookies-and-brownies]
349937,Cheesy Ground Beef and Rice Casserole,"[ground beef, medium onion chopped, brown rice...","[1 1/2 lbs ground beef, 1 medium onio...","[""*What I mean by ""partly drained"" with the mu...",6.0,1 (394 g),"[60-minutes-or-less, time-to-make, preparation]",1,394 g,[]